# Generated by Django 4.1.7 on 2023-03-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_password_customer_password1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='password1',
            new_name='pass1',
        ),
        migrations.AddField(
            model_name='customer',
            name='pass2',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
