# Generated by Django 4.1.7 on 2023-03-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_password1_customer_pass1_customer_pass2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='static/olx_photos/'),
        ),
    ]
