# Generated by Django 4.1.7 on 2023-03-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_customer_gender_customer_nationality_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='upload',
            field=models.ImageField(default='mob1.png', null=True, upload_to='static/olx_photos/'),
        ),
    ]
