# Generated by Django 4.1.7 on 2023-03-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_customer_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='upload',
            field=models.ImageField(default='mob1.png', null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
