# Generated by Django 4.1.7 on 2023-03-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_customer_upload_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='upload',
            field=models.ImageField(default='mob1.png', null=True, upload_to='prof_image'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(null=True, upload_to='olax'),
        ),
    ]
