# Generated by Django 4.1.7 on 2023-03-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_products_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='mob1.png', null=True, upload_to='products'),
        ),
    ]
